# -*- coding: utf-8 -*-
"""metro 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oW_7qN2lY7lL6nc1ntlGZTmefrqj_OIo
"""

!pip install ultralytics
!pip install supervision

from ultralytics import YOLO
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

model = YOLO("yolov8n.pt")

from google.colab import files
uploaded = files.upload()

import cv2
from google.colab.patches import cv2_imshow

video_path = "WhatsApp Video 2026-05-20 at 7.07.52 PM.mp4"

cap = cv2.VideoCapture(video_path)

ret, frame = cap.read()

cv2_imshow(frame)

cap.release()

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

# LOAD YOLO MODEL
model = YOLO("yolov8n.pt")

# VIDEO PATH
video_path = "WhatsApp Video 2026-05-20 at 7.07.52 PM.mp4"

cap = cv2.VideoCapture(video_path)

frame_count = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    # YOLO DETECTION
    results = model(frame)

    person_count = 0

    for r in results:

        boxes = r.boxes

        for box in boxes:

            cls = int(box.cls[0])

            # PERSON CLASS = 0
            if cls == 0:

                person_count += 1

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # DRAW RECTANGLE
                cv2.rectangle(frame,
                              (x1, y1),
                              (x2, y2),
                              (0,255,0),
                              2)

                # PERSON LABEL
                cv2.putText(frame,
                            "Person",
                            (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.5,
                            (0,255,0),
                            2)

    # SHOW PASSENGER COUNT
    cv2.putText(frame,
                f"Passengers: {person_count}",
                (20,40),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (255,0,0),
                3)

    # SHOW FRAME
    cv2_imshow(frame)

    frame_count += 1

    # SHOW ONLY 10 FRAMES
    if frame_count == 10:
        break

cap.release()

from ultralytics import YOLO
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# LOAD YOLO MODEL
model = YOLO("yolov8n.pt")

# VIDEO PATH
video_path = "WhatsApp Video 2026-05-20 at 7.07.52 PM.mp4"

cap = cv2.VideoCapture(video_path)

# -----------------------------------
# CORRECT SEAT POSITIONS
# -----------------------------------

seat_positions = [

    (120,430,25,90),
    (145,430,25,90),
    (170,430,25,90),
    (195,430,25,90),
    (220,430,25,90),

    (245,430,25,90),
    (270,430,25,90),
    (295,430,25,90),
    (320,430,25,90),
    (345,430,25,90),

    (370,430,25,90),
    (395,430,25,90),
    (420,430,25,90),
    (445,430,25,90),
    (470,430,25,90)


]

total_seats = len(seat_positions)

# STORE FINAL RESULTS
max_passenger_count = 0
minimum_empty_seats = total_seats

# -----------------------------------
# PROCESS COMPLETE VIDEO
# -----------------------------------

while True:

    ret, frame = cap.read()

    if not ret:
        break

    # YOLO DETECTION
    results = model(frame)

    people_boxes = []

    passenger_count = 0

    # -----------------------------
    # PERSON DETECTION
    # -----------------------------
    for r in results:

        boxes = r.boxes

        for box in boxes:

            cls = int(box.cls[0])

            # PERSON CLASS
            if cls == 0:

                passenger_count += 1

                x1,y1,x2,y2 = map(int, box.xyxy[0])

                people_boxes.append((x1,y1,x2,y2))

    # STORE MAX PASSENGERS
    if passenger_count > max_passenger_count:

        max_passenger_count = passenger_count

    # -----------------------------
    # EMPTY SEAT DETECTION
    # -----------------------------

    empty_seats = 0

    for sx,sy,sw,sh in seat_positions:

        occupied = False

        for px1,py1,px2,py2 in people_boxes:

            # PERSON CENTER POINT
            cx = (px1 + px2) // 2
            cy = (py1 + py2) // 2

            # CHECK CENTER INSIDE SEAT
            if (sx < cx < sx+sw and
                sy < cy < sy+sh):

                occupied = True
                break

        if not occupied:

            empty_seats += 1

    # STORE MINIMUM EMPTY SEATS
    if empty_seats < minimum_empty_seats:

        minimum_empty_seats = empty_seats

cap.release()

# -----------------------------------
# FINAL CROWD STATUS
# -----------------------------------

occupancy = max_passenger_count / total_seats

if occupancy >= 0.8:

    status = "CROWDED"

elif occupancy >= 0.5:

    status = "MODERATE"

else:

    status = "COMFORTABLE"

# -----------------------------------
# CREATE FINAL LED BOARD
# -----------------------------------

board = np.zeros((350,700,3), dtype=np.uint8)

# TITLE
cv2.putText(board,
            "METRO COMPARTMENT STATUS",
            (40,60),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,255,255),
            3)

# TOTAL PASSENGERS
cv2.putText(board,
            f"Total Passengers : {max_passenger_count}",
            (50,150),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (255,255,255),
            3)

# EMPTY SEATS
cv2.putText(board,
            f"Empty Seats : {minimum_empty_seats}",
            (50,220),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,255,0),
            3)

# CROWD STATUS
cv2.putText(board,
            f"Status : {status}",
            (50,290),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,0,255),
            3)

# SHOW FINAL LED BOARD
cv2_imshow(board)

# -----------------------------
# DISPLAY INFORMATION
# -----------------------------

# BLACK BACKGROUND BOX
cv2.rectangle(frame, (10,10), (450,190), (0,0,0), -1)

# PASSENGER COUNT
cv2.putText(frame,
            f"Passengers: {passenger_count}",
            (20,40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (255,255,255),
            3)

# TOTAL SEATS
cv2.putText(frame,
            f"Total Seats: {total_seats}",
            (20,80),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,255,255),
            3)

# EMPTY SEATS
cv2.putText(frame,
            f"Empty Seats: {empty_seats}",
            (20,120),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,255,0),
            3)

# CROWD STATUS
cv2.putText(frame,
            f"Status: {status}",
            (20,160),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,0,255),
            3)

import cv2
import numpy as np # Import numpy for creating a dummy frame if needed

# Assuming video_path is defined in a previous cell or globally
# If video_path is not defined, you might need to add it here, e.g., video_path = 'your_video.mp4'

# Ensure 'frame' is a valid image for processing
if 'frame' not in locals() or frame is None:
    if 'video_path' in locals() and video_path:
        cap_local = cv2.VideoCapture(video_path)
        ret, frame = cap_local.read()
        if not ret:
            print("Could not read a frame from the video. Creating a dummy black frame.")
            frame = np.zeros((720, 1280, 3), dtype=np.uint8) # Create a dummy 720p black frame
        cap_local.release()
    else:
        print("video_path is not defined and no frame is available. Creating a dummy black frame.")
        frame = np.zeros((720, 1280, 3), dtype=np.uint8) # Create a dummy 720p black frame

# SAVE FRAME
# Initialize cv2.VideoWriter if 'out' is not defined.
# For proper video saving, 'out' should be initialized once before a loop
# that processes all frames and then released after the loop.
if 'out' not in locals() and 'out' not in globals():
    # Get frame dimensions from the current 'frame'.
    height, width, _ = frame.shape
    # Define codec (e.g., 'mp4v' for .mp4 files) and desired frames per second (fps).
    fourcc = cv2.VideoWriter_fourcc(*'mp4v') # Codec for MP4 files
    fps = 30 # Example FPS, adjust as needed based on the source video
    output_filename = 'output_video.mp4' # Name of the output video file
    out = cv2.VideoWriter(output_filename, fourcc, fps, (width, height))

out.write(frame)

# SAVE FRAME
out.write(frame)

cap.release()
out.release()

print("Final Smart Metro AI Video Created!")

cv2.putText(frame,
            f"Status: {status}",
            (20,160),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0,0,255),
            3)

# SAVE FRAME
out.write(frame)

# END LOOP

cap.release()
out.release()

print("Final Smart Metro AI Video Created!")

from google.colab import files
files.download("output_video.mp4")

import os

# Create project folder
os.makedirs("Smart_Metro_AI_Project", exist_ok=True)

print("Folder Created")

